### ISSUE TITLE
Bindings project won't build because it confuses rustfmt.toml with some other config. Returns exit code 101.

### ISSUE THREAD

**Issue by NickelCoating** [robmikh/minesweeper-rs#22] opened 2020-07-17 18:49 UTC
For the record, this first appeared when I used bindings with my own project even after I only copied some code instead of just using the entire project. This is not an issue when the rustfmt.toml is in the bindings project folder, it only fails to build in a project that builds an exe and uses bindings, like Minesweeper and my own project.

As to why it confuses it with some other config file, I'm too fresh to Rust, still. I don't even know where, in Rust, in CLion in your code, or even in my code, this issue really lays. And CLion uses an additional Rust and Toml plugin, so...

Removing the rustfmt.toml file solved the exit code 101 issue:

```
Compiling bindings v0.1.0 (D:\_ Toy Maker\enamorf_showcase\enamorf_application\bindings)
error: failed to run custom build command for `bindings v0.1.0 (D:\_ ToyMaker\enamorf_showcase\enamorf_application\bindings)`

 Caused by:
  process didn't exit successfully: `D:\_ Toy Maker\enamorf_showcase\enamorf_application\target\release\build\bindings-4fc5abab444cf7ad\build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-changed=C:\Windows\System32\winmetadata\Windows.AI.winmd
cargo:rerun-if-changed=C:\Windows\System32\winmetadata\Windows.ApplicationModel.winmd
cargo:rerun-if-changed=C:\Windows\System32\winmetadata\Windows.Data.winmd
cargo:rerun-if-changed=C:\Windows\System32\winmetadata\Windows.Devices.winmd
cargo:rerun-if-changed=C:\Windows\System32\winmetadata\Windows.Foundation.winmd
cargo:rerun-if-changed=C:\Windows\System32\winmetadata\Windows.Gaming.winmd
cargo:rerun-if-changed=C:\Windows\System32\winmetadata\Windows.Globalization.winmd
cargo:rerun-if-changed=C:\Windows\System32\winmetadata\Windows.Graphics.winmd
cargo:rerun-if-changed=C:\Windows\System32\winmetadata\Windows.Management.winmd
cargo:rerun-if-changed=C:\Windows\System32\winmetadata\Windows.Media.winmd
cargo:rerun-if-changed=C:\Windows\System32\winmetadata\Windows.Networking.winmd
cargo:rerun-if-changed=C:\Windows\System32\winmetadata\Windows.Perception.winmd
cargo:rerun-if-changed=C:\Windows\System32\winmetadata\Windows.Security.winmd
cargo:rerun-if-changed=C:\Windows\System32\winmetadata\Windows.Services.winmd
cargo:rerun-if-changed=C:\Windows\System32\winmetadata\Windows.Storage.winmd
cargo:rerun-if-changed=C:\Windows\System32\winmetadata\Windows.System.winmd
cargo:rerun-if-changed=C:\Windows\System32\winmetadata\Windows.UI.Xaml.winmd
cargo:rerun-if-changed=C:\Windows\System32\winmetadata\Windows.UI.winmd
cargo:rerun-if-changed=C:\Windows\System32\winmetadata\Windows.Web.winmd

 --- stderr
Warning: Unknown configuration option `fn_params_layout`
Warning: Unknown configuration option `struct`
Error: Decoding config file failed:
invalid type: string "Max", expected struct WidthHeuristics for key `width_heuristics`
Please check your config file.
Warning: Unknown configuration option `fn_params_layout`
Warning: Unknown configuration option `struct`
Error: Decoding config file failed:
invalid type: string "Max", expected struct WidthHeuristics for key `width_heuristics`
Please check your config file.
thread 'main' panicked at 'Could not successfully build', bindings\build.rs:1:1
stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.46\src\backtrace\mod.rs:66
   1: std::sys_common::backtrace::_print_fmt
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2\/src\libstd\sys_common\backtrace.rs:78
   2: std::sys_common::backtrace::_print::{{impl}}::fmt
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2\/src\libstd\sys_common\backtrace.rs:59
   3: core::fmt::write
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2\/src\libcore\fmt\mod.rs:1076
   4: std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2\/src\libstd\io\mod.rs:1537
   5: std::sys_common::backtrace::_print
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2\/src\libstd\sys_common\backtrace.rs:62
   6: std::sys_common::backtrace::print
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2\/src\libstd\sys_common\backtrace.rs:49
   7: std::panicking::default_hook::{{closure}}
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2\/src\libstd\panicking.rs:198
   8: std::panicking::default_hook
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2\/src\libstd\panicking.rs:218
   9: std::panicking::rust_panic_with_hook
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2\/src\libstd\panicking.rs:486
  10: std::panicking::begin_panic
  11: alloc::alloc::box_free
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

Process finished with exit code 101
```

I can spot a "Error: Decoding config file failed:" twice. Seems there is nothing behind the colon even when it should!? Also note that my rustfm.toml file is actually longer, so some unknown config options aren't in that error. Maybe it actually reading false memory to begin with, not just the file path. That's my full file:

```
unstable_features = true
brace_style = "AlwaysNextLine"
control_brace_style = "AlwaysNextLine"
imports_layout = "Horizontal"
fn_params_layout = "Compressed"
where_single_line = true
width_heuristics = "Max"
struct = "Visual"
max_width = 200
```

Anyways... side info. I'm using CLion, Rust 1.45.0, and had Rust 1.44.1 previously, same error code 101, though.

**Comment by robmikh** [comment] 2020-07-17 19:16
Do you have a simplified repro I could look at? What does your directory structure look like? Does this happen when you try to build from the command line?

My first reaction is that this might be a CLion issue, but I've never really used it. However, I've also never used config files for fmt.

**Comment by NickelCoating** [comment] 2020-07-17 20:12
I just reproduced this error in VS Code and with Minesweeper. And yeah, it also had this issue in CLion via terminal. IDE as a cause can be excluded it seems.

I forked and added a Rust format file to Minesweeper to reproduce this error within this game: [My Fork](https://github.com/NickelCoating/minesweeper-rs)

And the file itself: [rustfmt.toml](https://github.com/NickelCoating/minesweeper-rs/blob/master/rustfmt.toml)

**Comment by rylev** [comment] 2020-07-17 21:13
The errors make it seems like you’re using config options for the upcoming release of rustfmt not the current stable version. You can find the config options here: https://rust-lang.github.io/rustfmt/?version=v1.4.17

**Comment by NickelCoating** [comment] 2020-07-17 22:19
Yeah, the more I think about it the more it seems to be Rust Format itself that is misbehaving. This got noting to do with actually compiling anything or reading a wrong config file like I first thought. The reason why not all handle as errors ain't false memory access but Rust Format that for some reason out of nowhere decided to do fatal errors instead of silent ones on features that are unstable.

Rust Format doesn't get that I use `unstable_features = true`!?

This issue is special to this specific project, and I wonder why. At first the format file only failed when placed in Minesweeper project like this. But now it also fails when placed in the bindings project when I try to build it.

For the record, I encountered a lot of other crates that got custom build scripts, namely those crates for OpenGL/Winapi/Vulkan, etc. but non of them have this issue. And this is specific to the build script!? None of my own code fails fatally. I got a couple of other projects in the same workspace, plus crates gl/glutin(OpenGL) and ash(Vulkan). Often code won't format at all. But those errors are silent.

Anyways, it's a Rust Format issue then. I will have to ask them for help. :)

**Comment by robmikh** [comment] 2020-07-17 22:45
Part of it may be that winrt-rs calls rustfmt directly from within the generated build function. Not that it's problematic itself, but it may explain a difference in behavior from other crates that generate bindings.

If you end up filing an issue with them, I'd be interested to know what the root cause is. Closing this issue for now.

**Closed by robmikh** 2020-07-17 22:45 UTC

**Comment by NickelCoating** [comment] 2020-07-18 09:32
I filed a bug issue for this problem at [rust-lang/rustfmt](https://github.com/rust-lang/rustfmt/issues/4333).
